# Generated by Django 5.2.3 on 2025-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('Comment', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('command_date', models.DateField()),
            ],
        ),
    ]
