# Generated by Django 5.2.3 on 2025-06-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_commentsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsModel',
        ),
    ]
